### ISSUE TITLE
SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by wolfch** [ahmadawais/corona-cli#61]
After installing I run just plain `corona` and get:
```
$ corona
C:\Users\cwolf\AppData\Roaming\npm\node_modules\corona-cli\index.js:36
(async () => {
       ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

```
$ node -v
v6.9.4
```

**Comment by harshit98** [comment]
It runs successfully on my machine. How did you installed it ?

**Comment by wolfch** [comment]
HI, thanks for responding here is the install output:

```
$ npm install -g corona-cli
C:\Users\cwolf\AppData\Roaming\npm\corona-cli -> C:\Users\cwolf\AppData\Roaming\npm\node_modules\corona-cli\index.js
C:\Users\cwolf\AppData\Roaming\npm\corona -> C:\Users\cwolf\AppData\Roaming\npm\node_modules\corona-cli\index.js
C:\Users\cwolf\AppData\Roaming\npm
`-- corona-cli@3.8.6
  +-- await-to-js@2.1.1
  +-- axios@0.19.2
  | `-- follow-redirects@1.5.10
  |   `-- debug@3.1.0
  |     `-- ms@2.0.0
  +-- chalk@3.0.0
  | +-- ansi-styles@4.2.1
  | | +-- @types/color-name@1.1.1
  | | `-- color-convert@2.0.1
  | |   `-- color-name@1.1.4
  | `-- supports-color@7.1.0
  |   `-- has-flag@4.0.0
  +-- cli-handle-error@4.1.0
  +-- cli-table3@0.5.1
  | +-- colors@1.4.0
  | +-- object-assign@4.1.1
  | `-- string-width@2.1.1
  |   +-- is-fullwidth-code-point@2.0.0
  |   `-- strip-ansi@4.0.0
  |     `-- ansi-regex@3.0.0
  +-- cli-welcome@1.4.0
  | +-- chalk@2.4.2
  | | +-- ansi-styles@3.2.1
  | | | `-- color-convert@1.9.3
  | | |   `-- color-name@1.1.3
  | | +-- escape-string-regexp@1.0.5
  | | `-- supports-color@5.5.0
  | |   `-- has-flag@3.0.0
  | `-- clear-any-console@1.16.0
  +-- comma-number@2.0.1
  +-- lodash.orderby@4.6.0
  +-- log-symbols@3.0.0
  | `-- chalk@2.4.2
  |   +-- ansi-styles@3.2.1
  |   | `-- color-convert@1.9.3
  |   |   `-- color-name@1.1.3
  |   `-- supports-color@5.5.0
  |     `-- has-flag@3.0.0
  +-- meow@6.1.0
  | +-- @types/minimist@1.2.0
  | +-- camelcase-keys@6.2.1
  | | +-- camelcase@5.3.1
  | | +-- map-obj@4.1.0
  | | `-- quick-lru@4.0.1
  | +-- decamelize-keys@1.1.0
  | | +-- decamelize@1.2.0
  | | `-- map-obj@1.0.1
  | +-- hard-rejection@2.1.0
  | +-- minimist-options@4.0.2
  | | +-- arrify@1.0.1
  | | `-- is-plain-obj@1.1.0
  | +-- normalize-package-data@2.5.0
  | | +-- hosted-git-info@2.8.8
  | | +-- resolve@1.15.1
  | | | `-- path-parse@1.0.6
  | | +-- semver@5.7.1
  | | `-- validate-npm-package-license@3.0.4
  | |   +-- spdx-correct@3.1.0
  | |   | `-- spdx-license-ids@3.0.5
  | |   `-- spdx-expression-parse@3.0.0
  | |     `-- spdx-exceptions@2.2.0
  | +-- read-pkg-up@7.0.1
  | | +-- find-up@4.1.0
  | | | +-- locate-path@5.0.0
  | | | | `-- p-locate@4.1.0
  | | | |   `-- p-limit@2.2.2
  | | | |     `-- p-try@2.2.0
  | | | `-- path-exists@4.0.0
  | | `-- read-pkg@5.2.0
  | |   +-- @types/normalize-package-data@2.4.0
  | |   +-- parse-json@5.0.0
  | |   | +-- @babel/code-frame@7.8.3
  | |   | | `-- @babel/highlight@7.9.0
  | |   | |   +-- @babel/helper-validator-identifier@7.9.0
  | |   | |   +-- chalk@2.4.2
  | |   | |   | +-- ansi-styles@3.2.1
  | |   | |   | | `-- color-convert@1.9.3
  | |   | |   | |   `-- color-name@1.1.3
  | |   | |   | `-- supports-color@5.5.0
  | |   | |   |   `-- has-flag@3.0.0
  | |   | |   `-- js-tokens@4.0.0
  | |   | +-- error-ex@1.3.2
  | |   | | `-- is-arrayish@0.2.1
  | |   | +-- json-parse-better-errors@1.0.2
  | |   | `-- lines-and-columns@1.1.6
  | |   `-- type-fest@0.6.0
  | +-- redent@3.0.0
  | | +-- indent-string@4.0.0
  | | `-- strip-indent@3.0.0
  | |   `-- min-indent@1.0.0
  | +-- trim-newlines@3.0.0
  | +-- type-fest@0.8.1
  | `-- yargs-parser@18.1.2
  +-- ora@4.0.3
  | +-- cli-cursor@3.1.0
  | | `-- restore-cursor@3.1.0
  | |   +-- onetime@5.1.0
  | |   | `-- mimic-fn@2.1.0
  | |   `-- signal-exit@3.0.3
  | +-- cli-spinners@2.2.0
  | +-- is-interactive@1.0.0
  | +-- mute-stream@0.0.8
  | +-- strip-ansi@6.0.0
  | | `-- ansi-regex@5.0.0
  | `-- wcwidth@1.0.1
  |   `-- defaults@1.0.3
  |     `-- clone@1.0.4
  `-- update-notifier@4.1.0
    +-- boxen@4.2.0
    | +-- ansi-align@3.0.0
    | | `-- string-width@3.1.0
    | |   +-- emoji-regex@7.0.3
    | |   `-- strip-ansi@5.2.0
    | |     `-- ansi-regex@4.1.0
    | +-- cli-boxes@2.2.0
    | +-- string-width@4.2.0
    | | +-- emoji-regex@8.0.0
    | | +-- is-fullwidth-code-point@3.0.0
    | | `-- strip-ansi@6.0.0
    | |   `-- ansi-regex@5.0.0
    | +-- term-size@2.2.0
    | `-- widest-line@3.1.0
    |   `-- string-width@4.2.0
    |     +-- emoji-regex@8.0.0
    |     +-- is-fullwidth-code-point@3.0.0
    |     `-- strip-ansi@6.0.0
    |       `-- ansi-regex@5.0.0
    +-- configstore@5.0.1
    | +-- dot-prop@5.2.0
    | | `-- is-obj@2.0.0
    | +-- graceful-fs@4.2.3
    | +-- make-dir@3.0.2
    | | `-- semver@6.3.0
    | +-- unique-string@2.0.0
    | | `-- crypto-random-string@2.0.0
    | `-- write-file-atomic@3.0.3
    |   +-- imurmurhash@0.1.4
    |   +-- is-typedarray@1.0.0
    |   `-- typedarray-to-buffer@3.1.5
    +-- has-yarn@2.1.0
    +-- import-lazy@2.1.0
    +-- is-ci@2.0.0
    | `-- ci-info@2.0.0
    +-- is-installed-globally@0.3.1
    | +-- global-dirs@2.0.1
    | | `-- ini@1.3.5
    | `-- is-path-inside@3.0.2
    +-- is-npm@4.0.0
    +-- is-yarn-global@0.3.0
    +-- latest-version@5.1.0
    | `-- package-json@6.5.0
    |   +-- got@9.6.0
    |   | +-- @sindresorhus/is@0.14.0
    |   | +-- @szmarczak/http-timer@1.1.2
    |   | | `-- defer-to-connect@1.1.3
    |   | +-- cacheable-request@6.1.0
    |   | | +-- clone-response@1.0.2
    |   | | +-- get-stream@5.1.0
    |   | | +-- http-cache-semantics@4.1.0
    |   | | +-- keyv@3.1.0
    |   | | | `-- json-buffer@3.0.0
    |   | | +-- lowercase-keys@2.0.0
    |   | | +-- normalize-url@4.5.0
    |   | | `-- responselike@1.0.2
    |   | +-- decompress-response@3.3.0
    |   | +-- duplexer3@0.1.4
    |   | +-- get-stream@4.1.0
    |   | | `-- pump@3.0.0
    |   | |   +-- end-of-stream@1.4.4
    |   | |   `-- once@1.4.0
    |   | |     `-- wrappy@1.0.2
    |   | +-- lowercase-keys@1.0.1
    |   | +-- mimic-response@1.0.1
    |   | +-- p-cancelable@1.1.0
    |   | +-- to-readable-stream@1.0.0
    |   | `-- url-parse-lax@3.0.0
    |   |   `-- prepend-http@2.0.0
    |   +-- registry-auth-token@4.1.1
    |   | `-- rc@1.2.8
    |   |   +-- deep-extend@0.6.0
    |   |   +-- minimist@1.2.5
    |   |   `-- strip-json-comments@2.0.1
    |   +-- registry-url@5.1.0
    |   `-- semver@6.3.0
    +-- pupa@2.0.1
    | `-- escape-goat@2.1.1
    +-- semver-diff@3.1.1
    | `-- semver@6.3.0
    `-- xdg-basedir@4.0.0
```

**Comment by wolfch** [comment]
Let me try on Linux

**Comment by ahmadawais** [comment]
You should be using Node v12 or greater.

>

**Comment by wolfch** [comment]
It worked on Ubuntu-18 with node `v10.19.0`.  So it won't work (at least on Windoze) with Node `v6.9.4`.  I'll try to upgrade node on Windoze to see if that helps.  Thanks...

**Comment by cosinekitty** [comment]
Node introduced async/await in version 7.6:

https://www.infoq.com/news/2017/02/node-76-async-await/

It won't matter whether it is running Windows, Mac OS, or Linux. On any of these operating systems, it is pretty easy to install the latest LTS version (currently 12.16.1), by following instructions at https://nodejs.org/ .

**Comment by ahmadawais** [comment]
Please update Node.js to the latest stable version. You're at a security risk otherwise.

**Comment by wolfch** [comment]
It worked on Windoze after installing latest NodeJS, thanks for your help and the URL for async/await.

**Comment by ahmadawais** [comment]
I'm adding a new message of error if someone tries to run it below v12.
Soonish.

>

**Comment by wolfch** [comment]
Ok, but it worked for me with `v10.19.0` on Linux, but it's good that you plan to warn about minimum supported version.

**Comment by ahmadawais** [comment]
It probably works on v8 and beyond but why support an old deprecated
version of Node — that's anything but safe to use?

**Comment by wolfch** [comment]
There could be lot of explanations why a particular user or organization might be stuck in a legacy situation.  For example, I've worked for investment banks and their IT are very wary of adopting the latest and greatest.  Otherwise, sure, I agree with you.

**Comment by ahmadawais** [comment]
Yeah sure. Sadly as a free and open-source software creator that doesn't concern me. If enterprise that's stuck with legacy software wants to pay top dollar to make me support this CLI on their legacy systems, sure. Otherwise, who cares.

**Comment by wolfch** [comment]
Sure, I personally would avoid legacy also.  :)
